# Generated by Django 4.0.2 on 2022-02-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WomenConfig',
            new_name='Women',
        ),
    ]
